version: "3.1"

services:
  web:
    image: nginx
    volumes:
      - ./qd.conf.tmpl:/etc/nginx/conf.d/qd.conf.tmpl
      - "./ui/dist/spa:/data/site"
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=${HOST}
      - NGINX_PORT=80
      - API_HOST=api
      - API_PORT=9090
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/qd.conf.tmpl > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - api

  importer:
    restart: on-failure
    image: quick-draw-explorer_api:latest
    volumes:
      - "./quick-draw.csv:/quick-draw.csv"
    command:
      - "--import"
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - ALLOWED_CORS_URLS=http://${HOST}
      - API_HOST=0.0.0.0
      - API_PORT=9090
    depends_on:
      - db
    expose:
      - "9090"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: quickdraw
    volumes:
      - "./db-init:/docker-entrypoint-initdb.d"
    expose:
      - "5432"
  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - "9000:8080"
